name: TaskFlow CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Kod repository'den çekiliyor
      uses: actions/checkout@v4
      
    - name: .NET 9 SDK Yükleniyor
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Bağımlılıklar Geri Yükleniyor (Restore)
      run: dotnet restore
      
    - name: Proje Derleniyor (Build)
      run: dotnet build --no-restore --configuration Release
      
    - name: Unit ve Integration Testler Çalıştırılıyor
      run: dotnet test --no-build --configuration Release --verbosity normal